FROM php:8.2-cli

WORKDIR /app

# instalar dependencias
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    curl

# instalar composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install

EXPOSE 8000

CMD php artisan serve --host=0.0.0.0 --port=8000