FROM python:3.12-slim

WORKDIR /app

COPY actiscan_fastapi/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY actiscan_fastapi/ .
COPY ["actiscan (1).sql", "/app/actiscan (1).sql"]

EXPOSE 8001

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
